### ISSUE TITLE
List Dependencies Problem (not found)

### ISSUE THREAD

**Issue by gianfelicevincenzo** [naufraghi/pdf2dxf#1]
`Traceback (most recent call last):
  File "./pdf2dxf.py", line 20, in <module>
    svg = importlib.import_module("svg")
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'svg'`

In addition, you can also write a "requirements.txt" file for all dependencies that the script has!

**Comment by naufraghi** [comment]
Hi @vincenzogianfelice , this project uses [`poetry`](https://python-poetry.org/) as packaging system and `pyptoject.toml` to list the dependencies.

If it is OK for you I'd change this issue title in:

> Add a note about poetry usage in the readme

**Comment by gianfelicevincenzo** [comment]
Ah ok... it is the first I hear of poetry :)

**Comment by naufraghi** [comment]
`poetry` and `pyproject.toml` are a superset / substitute of a submodule or a `requirements.txt` file, just execute `poetry install` or `poetry shell` to start a virtual env with your deps installed.

But please, be more constructive, you are free to "highly **recommend**" to someone you know or someone that owes you something, not to a stranger on the net that shared for free something you may find useful but you dislike for some reason.

(while I was writing you changed the previous comment, in a better way, thanks!)

**Comment by gianfelicevincenzo** [comment]
Scusami ... in effetti ho capito l'errore e l'ho subito corretto. Non avevo mai sentito parlare di poetry e in effetti solo ora ho dato una rapida occhiata ... Pensavo di modificare il commento prima che tu lo leggessi ... ma non ce l'ho fatta in tempo :). Scusami di nuovo

**Comment by naufraghi** [comment]
The first version of the comment is (may be) notified by mail, be aware of this :)

**Comment by gianfelicevincenzo** [comment]
I was hoping you hadn't turned on email notification :)
Sorry
