### ISSUE TITLE
cannot execute code

### ISSUE THREAD

**Issue by ftmzhrsckldr** [naufraghi/pdf2dxf#2]
Can I ask which command you run the code with?

**Comment by naufraghi** [comment]
Hi, sorry for the delay.

The code is a Python script, you can run `python3 pdf2dxf.py some.pdf some.dxf` or, without Python, you can use the bundle committed in `pdf2dxf/pdfalto/win32/pdfalto.exe` / `pdf2dxf/pdfalto/linux/pdfalto`.
That bundle is the same exact script, packed using PyInstaller with the [`pdfalto`](https://github.com/kermitt2/pdfalto) executable that does the most.
