### ISSUE TITLE
Error while loading shared libraries: libz.so.1: failed to map segment from shared object (Ubuntu 20.04)

### ISSUE THREAD

**Issue by thima2017** [naufraghi/pdf2dxf#3]
Where could I find a sources of pdfalto?

Console output:
$ python3 ./pdf2dxf.py ./SPB_L01\(38\).pdf ./SPB_L01\(38\).dxf
DEBUG:__main__:Iterating svgs from /media/user/11828f6f-0a0f-43b6-9985-1a87a0dbf845/user/bouilds/pdf2dxf/pdf2dxf-master/SPB_L01(38).pdf
DEBUG:__main__:In /tmp/tmpqmq1jpas.pdfimport...
DEBUG:__main__:Spawning /media/user/11828f6f-0a0f-43b6-9985-1a87a0dbf845/user/bouilds/pdf2dxf/pdf2dxf-master/pdfalto/linux/pdfalto /media/user/11828f6f-0a0f-43b6-9985-1a87a0dbf845/user/bouilds/pdf2dxf/pdf2dxf-master/SPB_L01(38).pdf out.xml
/media/user/11828f6f-0a0f-43b6-9985-1a87a0dbf845/user/bouilds/pdf2dxf/pdf2dxf-master/pdfalto/linux/pdfalto: error while loading shared libraries: libz.so.1: failed to map segment from shared object
Traceback (most recent call last):
  File "./pdf2dxf.py", line 130, in <module>
    run()
  File "./pdf2dxf.py", line 122, in run
    for c, (svg_path, size_wh) in enumerate(iter_svg_from_pdf(args.pdf)):
  File "./pdf2dxf.py", line 93, in iter_svg_from_pdf
    subprocess.check_call(args)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/media/user/11828f6f-0a0f-43b6-9985-1a87a0dbf845/user/bouilds/pdf2dxf/pdf2dxf-master/pdfalto/linux/pdfalto', '/media/user/11828f6f-0a0f-43b6-9985-1a87a0dbf845/user/bouilds/pdf2dxf/pdf2dxf-master/SPB_L01(38).pdf', 'out.xml']' returned non-zero exit status 127.

**Comment by naufraghi** [comment]
You are right, there is no link in the readme, here is the repo: https://github.com/kermitt2/pdfalto

The problem seems related with the `noexec` mount option of `/tmp`, that may be a new default of Ubuntu 20.04?

**Comment by thima2017** [comment]
Yes, remount,exec solved the issue, thank you. 

My current issue is in memory consumption. I have 16 Gb and a swap partition. While converting my system memory is full and swap has more than 5 Gb of something. System monitor shows that pdf2dxf took 14 Gb. My pdf file to convert is about 5,5 Mb. It's made in AutoCad 2019 by pdfplot15.hdi 15.00.103.000 producer. 

And I found that it's needed to change string 86 in pdf2dxf.py from
      ``` pdfalto = os.path.abspath(os.path.join(HERE, f'../../lib/pdfalto/{sys.platform}', exe)) ```
to
        ```pdfalto = os.path.abspath(os.path.join(HERE, f'pdfalto/{sys.platform}', exe))```
And I added symlink from pdfalto to pdf2dxf in pdfalto/linux directory.

No, seems it was me who add noexec option to /tmp. It's still not a default.
The new thing about /tmp in Lubuntu 20.04 is that /tmp mounts to tmpfs by default on my system (I guess it takes in account the amount of system memory). Mini net install iso don't act like that.

**Comment by naufraghi** [comment]
The `noexec` support may be a thing to do, as it can be preferred for security reasons. It's still to investigate if this is a `pdfalto`, `PyInstaller` or this script problem.

**Comment by thima2017** [comment]
It's PyInstaller https://github.com/pyinstaller/pyinstaller/issues/3870.
For some reason AppImages aren't affected by noexec. I've tried with FreeCAD AppImage. I even was able to run the unpacked executables manually. I don't know how it works.
