### ISSUE TITLE
vector text information was also converted to SVG  <path>

### ISSUE THREAD

**Issue by HardenGale** [naufraghi/pdf2dxf#5]
I successfully ran your program on Linux, and my PDF was successfully converted to DXF, but the text information in the DXF was obtained by splicing polylines. I found that in the Pdfalto project, the vector information in the PDF was converted to SVG, but the vector text information was also converted to SVG and represented by PATH. I tried to solve it, but failed. How can I ensure that the text in the DXF can be displayed correctly during the PDF2DXF process?

**Comment by naufraghi** [comment]
I'm sorry, when I wrote this I was not interested in the text, I did not have a look how to process the text differently.
